export const GET_PRODUCTS_LOADING = "GET_PRODUCTS_LOADING"
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR"
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS"

export const GET_SINGLE_PRODUCT_SUCCESS = "GET_SINGLE_PRODUCT_SUCCESS"


export const GET_CART_PRODUCTS_LOADING = "GET_CART_PRODUCTS_LOADING"
export const GET_CART_PRODUCTS_ERROR = "GET_CART_PRODUCTS_ERROR"
export const GET_CART_PRODUCTS_SUCCESS = "GET_CART_PRODUCTS_SUCCESS"
export const DEC_CART_PRODUCTS_SUCCESS = "DEC_CART_PRODUCTS_SUCCESS"
export const INC_CART_PRODUCTS_SUCCESS = "INC_CART_PRODUCTS_SUCCESS"

export const SET_USER_ADDRESS = "SET_USER_ADDRESS"
export const SET_SIGNUP_USERDATA = "SET_SIGNUP_USERDATA"

export const SET_USER_LOGIN_SUCCESS = "SET_USER_LOGIN_SUCCESS"
export const SET_USER_LOGOUT_SUCCESS = "SET_USER_LOGOUT_SUCCESS"

//WishList Action Type
export const GET_WISHLIST_DATA_LOADING = "GET_WISHLIST_DATA_LOADING"
export const GET_WISHLIST_DATA_ERROR = "GET_WISHLIST_DATA_ERROR"
export const GET_WISHLIST_DATA_SUCCESS = "GET_WISHLIST_DATA_SUCCESS"

export const ADD_WISHLIST_DATA_SUCCESS = "ADD_WISHLIST_DATA_SUCCESS"
export const REMOVE_WISHLIST_DATA_SUCCESS = "REMOVE_WISHLIST_DATA_SUCCESS"





// export const EMPTY_CART = "EMPTY_CART"

// export const SET_CARD_DATA = "SET_CARD_DATA"