export const GET_PRODUCTS_LOADING = "GET_PRODUCTS_LOADING"
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR"
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS"

export const GET_SINGLE_PRODUCT_SUCCESS = "GET_SINGLE_PRODUCT_SUCCESS"


export const GET_CART_PRODUCTS_LOADING = "GET_CART_PRODUCTS_LOADING"
export const GET_CART_PRODUCTS_ERROR = "GET_CART_PRODUCTS_ERROR"
export const GET_CART_PRODUCTS_SUCCESS = "GET_CART_PRODUCTS_SUCCESS"
export const DEC_CART_PRODUCTS_SUCCESS = "DEC_CART_PRODUCTS_SUCCESS"
export const INC_CART_PRODUCTS_SUCCESS = "INC_CART_PRODUCTS_SUCCESS"

